name: Download Model with Cache

on: [push]  # Trigger on every push to the repo (you can adjust triggers)

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install gdown
      run: pip install gdown

    - name: Cache model
      uses: actions/cache@v2
      with:
        path: model_file  # Path to where the model should be saved
        key: model-cache-key
        restore-keys: |
          model-cache-key

    - name: Download model from Google Drive if cache is missing
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        file_id="1xqslhXPzlymHSd22xh6-u-tLLNhR4TZu"
        url="https://drive.google.com/uc?id=${file_id}"
        gdown "$url" -O model_file  # Replace with actual model file name

    - name: Upload model as artifact
      uses: actions/upload-artifact@v2
      with:
        name: model-file
        path: model_file
