name: Download Model with Cache

on: [push]

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install gdown
      run: pip install gdown

    - name: Create models directory
      run: mkdir -p ./models  # Create the 'models' directory

    - name: Cache model
      uses: actions/cache@v2
      with:
        path: ./models/fine_tuned_xray_model_280.keras
        key: ${{ runner.os }}-model-cache-key-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-model-cache-key-

    - name: Download model from Google Drive if cache is missing
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        file_id="1xqslhXPzlymHSd22xh6-u-tLLNhR4TZu"
        url="https://drive.google.com/uc?id=${file_id}"
        gdown "$url" -O ./models/fine_tuned_xray_model_280.keras  # Correct model file name

    - name: Upload model as artifact
      uses: actions/upload-artifact@v2
      with:
        name: model-file
        path: ./models/fine_tuned_xray_model_280.keras
